### ISSUE TITLE
Something about complex combining

### ISSUE THREAD

**Issue by saeziae** [norto/taitham-lanna#2]
The font cannot display combining letters like "hluang" correctly.
![Screenshot from 2019-06-24 11-56-33](https://user-images.githubusercontent.com/26759054/59990790-28207080-9677-11e9-8b8d-17b037feb70c.png)

**Comment by norto** [comment]
> The font cannot display combining letters like "hluang" correctly.
> ![Screenshot from 2019-06-24 11-56-33](https://user-images.githubusercontent.com/26759054/59990790-28207080-9677-11e9-8b8d-17b037feb70c.png)

Hi Saeziae, 

The spelling of 'hluang' is always a topic of debate. But I can say that it is due to the regional differences.

ᩉᩖ᩠ᩅᨦ ᩉ᩠ᩃ᩠ᩅᩃ  = Lanna (Thai) preferred spelling which prefers the 3 stacks

ᩉᩖᩅ᩠ᨦ  ᩉ᩠ᩃᩅ᩠ᨦ  = ancient spelling. The first record of the word hluang was written in this form, and it still considered correct in some region of Thailand, for example Chiang Rai and Nan province.

ᩉᩖᨦ᩠ᩅ ᩉ᩠ᩃᨦ᩠ᩅ = Khün, Lue preferred spelling, better legibility.

And these 3 spellings are all correct for Lanna (Thai) spelling convention. NS Tahlom font now follows the aesthtic of Lanna (Thai), so, I have to make the font to support all 3 spellings by not sifting ᩅ (wa) like in Khün/Lue style font. You can still type ᩉᩖᨦ᩠ᩅ by input the character following this order : ᩉ + ᩃ + ᨦ + ᩅ 

I understand that this might look counter-intuitive and not so practical for Khün/Lue user, but it is the only way to make all 3 spellings possible, and this will cause the problem when you change between font from Khün/Lue to Lanna style. For example A Tai Tham KH to NS Tahlom.

In fact, there are lots of differences between Lanna (Thai) and Khün/Lue spelling conventions. I attach the picture in case  you could not render the Tai Tham font.

Anyway, could you tell me which region you are from? So we could discuss more about the writing system you use (Khuen, Lue, etc.) and what is the purpose for you to use Tai Tham script.

Thank you.

![Lanna](https://user-images.githubusercontent.com/28560445/60029597-bf9ab900-96a1-11e9-9723-ea05f576f87e.JPG)

**Comment by saeziae** [comment]
However, the word "wat-che-di-luang"(วัดเจดีหลวง) I see in Chiang Mai is spelt in the third form (undoubtedly it is Lanna) :
![IMG_20190128_122224](https://user-images.githubusercontent.com/26759054/60070093-004d0d80-9748-11e9-8e09-a5a1a0d44fb9.jpg)
- - - -
Moreover, what about "klua", if inputed as "ᨠᩖᩫ᩠ᩅ" (ก-ล--ົ-ว), it won't display normally like ᨠᩖ᩠ᩅᩫ(ก-ล-ว--ົ), or does it have another form in Lanna? (In Khuen it is spelt as "ᨠᩫ᩠ᩅ")
- - - -
P.S.: I am from China, and interested in Tai language. Urh, I mean, I may use all Lanna(CM), Khuen and Sipsongpanna Tai. I prefer to change the style by changing the font.

**Comment by norto** [comment]
In Thailand, you can find all 3 spellings: ᩉᩖ᩠ᩅᨦ (40%) ᩉᩖᨦ᩠ᩅ (30%) ᩉᩖᩅ᩠ᨦ (10%) and others (10%). that's why I use the word "preferable". ᩉᩖ᩠ᩅᨦ (triple-stack) appears more often in the literature rather than temple sign. (see below the text)

Actually there are more than that 3 spellings exits in Thailand right now, for example ᩉ᩠ᩃᩅ᩠ᨦᩫ or ᩉ᩠ᩃᨦ᩠ᩅᩫ due to the lack of the standardization; these spellings occur rarely.

For กลัว, in Lanna only the form ᨠᩖ᩠ᩅᩫ or ᨠ᩠ᩃ᩠ᩅᩫ are considered correct. And you cannot input in this "ก-ล--ົ-ว" order because it is forbided by the universal shaping engine. I mean, it's the incorrect way to input, following the unicode rule. The input method of Tai tham is "logical input" not "visual input" (like Thai, Roman). And logical here doesn't mean human logic but rather the "computer logic". I suggest you read this document:  https://www.unicode.org/L2/L2007/07007r-n3207r-lanna.pdf  which explain the correct input order of Tai Tham script by unicode

"ก-ล--ົ-ว" makes wrong rendering because  -ົ- is in the middle of the stack, it disrupts the stack rendering. Thus, "ก-ล-ว--ົ " is the only correct input order. This is also true for non-tripple-stack. The correct input order of ᨠ᩠ᩅᩫ is actually  "ก-ว--ົ " 

Why? --> because it's logical input order and the order is:  consonant - vowel (side) - consonant(below) - vowel (above) - tonal/sign (above) . Something like that.

I know that there is a problem between Tai Tham Lanna style and Khuen/Lue style that make it unable to make 1 font suitable for both styles in the same time. It's not that easy because Lanna and Khuen spelling conventions are different. The pronunciations are different (even if it's intelligible, but different enough to have a distinct feature).

I am always thinking to make the khuen version of my font too but do not have much time to even manage the current font. But the summer holidays are coming, I hope that I will have time for the Khuen version and also the update to the font. :-)

These are very interesting documents on the analysis of Tai tham spelling variations
https://www.unicode.org/L2/L2018/18171-vowels-below.pdf
https://unicodeconference.org/39/presentations/S3-T3-Chew.pdf

![2013-01-24 09 41 24](https://user-images.githubusercontent.com/28560445/60363350-99e41b80-99e3-11e9-9d67-950e05d96222.jpg)

![2019-06-25 09 39 18](https://user-images.githubusercontent.com/28560445/60363384-a799a100-99e3-11e9-859b-4245cae3e8e2.png)

![2017-02-01 16 33 01](https://user-images.githubusercontent.com/28560445/60363365-9e103900-99e3-11e9-813b-c8af270f6bd6.jpg)

![2019-06-25 09 15 06](https://user-images.githubusercontent.com/28560445/60363392-ae281880-99e3-11e9-9974-4c24b491655f.png)

![2019-06-25 08 57 06](https://user-images.githubusercontent.com/28560445/60363397-b1bb9f80-99e3-11e9-99f2-fecd55f73a48.jpg)
